import type { PlanLimits, PlanName } from "@/types"

export const PLAN_LIMITS: Record<PlanName, PlanLimits> = {
  free: {
    maxProjects: 1,
    manualRunsPerMonth: 5,
    scheduledRuns: false,
    hourlyRuns: false,
    emailAlerts: false,
    pdfReports: false,
    slackAlerts: false,
    historyDays: 7,
    aiActionPlansPerMonth: 0,
    maxPagesPerProject: 2,
  },
  starter: {
    maxProjects: 5,
    manualRunsPerMonth: -1,
    scheduledRuns: true,
    hourlyRuns: false,
    emailAlerts: true,
    pdfReports: false,
    slackAlerts: false,
    historyDays: 30,
    aiActionPlansPerMonth: 5,
    maxPagesPerProject: 10,
  },
  pro: {
    maxProjects: 20,
    manualRunsPerMonth: -1,
    scheduledRuns: true,
    hourlyRuns: true,
    emailAlerts: true,
    pdfReports: true,
    slackAlerts: true,
    historyDays: 90,
    aiActionPlansPerMonth: 30,
    maxPagesPerProject: 50,
  },
  agency: {
    maxProjects: 100,
    manualRunsPerMonth: -1,
    scheduledRuns: true,
    hourlyRuns: true,
    emailAlerts: true,
    pdfReports: true,
    slackAlerts: true,
    historyDays: 365,
    aiActionPlansPerMonth: -1,
    maxPagesPerProject: -1,
  },
}
